# Generated by Django 5.2.15 on 2026-07-05 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nominee_name",
                    models.CharField(
                        blank=True,
                        help_text="Used when the nominee isn't a Person yet.",
                        max_length=255,
                    ),
                ),
                ("nominee_organization", models.CharField(blank=True, max_length=255)),
                ("rationale", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="events.event",
                    ),
                ),
                (
                    "nominator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nominations_made",
                        to="people.person",
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nominations_received",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("nominee__isnull", False),
                            models.Q(("nominee_name", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="nomination_has_a_nominee_or_a_name",
                    )
                ],
            },
        ),
    ]
