# Generated by Django 5.2.15 on 2026-07-05 21:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("main_conference", "Main Conference"),
                            ("curated_side_event", "Curated Side Event"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("event_date", models.DateField()),
                (
                    "target_capacity",
                    models.PositiveIntegerField(help_text="Actual number of seats."),
                ),
                (
                    "historical_show_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.800"),
                        help_text="Fraction of acceptances that historically actually show up.",
                        max_digits=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
    ]
