# Generated by Django 5.2.15 on 2026-07-05 20:57

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "person_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                ("organization", models.CharField(blank=True, max_length=255)),
                (
                    "sector_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "seniority_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("c_level", "C-Level"),
                            ("senior_executive", "Senior Executive"),
                            ("management", "Management"),
                            ("staff", "Mitarbeiter"),
                            ("other", "Sonstige"),
                        ],
                        max_length=32,
                    ),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("given", "Eingewilligt"),
                            ("revoked", "Widerrufen"),
                            ("unclear", "Unklar"),
                        ],
                        default="unclear",
                        max_length=16,
                    ),
                ),
                ("data_retention_note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="absorbed_persons",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.PositiveSmallIntegerField()),
                (
                    "reasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Offen"),
                            ("confirmed", "Bestätigt (zusammengeführt)"),
                            ("rejected", "Abgelehnt (kein Duplikat)"),
                            ("obsolete", "Hinfällig"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, max_length=255)),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates_as_a",
                        to="people.person",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidates_as_b",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "email"],
            },
        ),
        migrations.CreateModel(
            name="PersonMergeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("moved_emails", models.JSONField(default=list)),
                ("rationale", models.TextField(blank=True)),
                ("performed_by", models.CharField(blank=True, max_length=255)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                ("reverted_by", models.CharField(blank=True, max_length=255)),
                (
                    "duplicate_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.duplicatecandidate",
                    ),
                ),
                (
                    "source_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merge_log_as_source",
                        to="people.person",
                    ),
                ),
                (
                    "target_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merge_log_as_target",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("merged_into", models.F("person_id")), _negated=True
                ),
                name="person_cannot_merge_into_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.UniqueConstraint(
                fields=("person_a", "person_b"), name="unique_duplicate_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="personemail",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unique_person_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="personemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("person",),
                name="one_primary_email_per_person",
            ),
        ),
    ]
