# Generated by Django 5.2.15 on 2026-07-06 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PersonDeletionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_by",
                    models.CharField(
                        blank=True,
                        help_text="The data subject, or whoever raised the request.",
                        max_length=255,
                    ),
                ),
                ("performed_by", models.CharField(max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deletion_logs",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deletion log",
                "ordering": ["-performed_at"],
            },
        ),
    ]
