# Generated by Django 5.2.15 on 2026-07-05 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("promoted_from_waitlist", "Promoted from waitlist"),
                            ("no_show", "No-show"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("platform", "Self-service platform"),
                            ("email", "Email"),
                            ("manual", "Manual"),
                            ("excel_import", "Excel import"),
                            ("nomination", "Nomination approval"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_note", models.TextField(blank=True)),
                (
                    "tracking_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "conversation_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_events",
                        to="events.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invitation_events",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_code", models.CharField(blank=True, max_length=64)),
                (
                    "conversation_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("raw_body", models.TextField()),
                ("received_at", models.DateTimeField()),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("ambiguous", "Ambiguous (needs review)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("resolved_by", models.CharField(blank=True, max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_replies",
                        to="events.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_replies",
                        to="people.person",
                    ),
                ),
                (
                    "resulting_invitation_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="invitations.invitationevent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email replies",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="StandbyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standby_contacts",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
