# Generated by Django 5.2.15 on 2026-07-05 23:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatingWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector_diversity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                (
                    "seniority_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                (
                    "relationship_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=4
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_weights",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeatPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_pins",
                        to="events.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_pins",
                        to="people.person",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_pins",
                        to="seating.table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_by", models.CharField(blank=True, max_length=255)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_assignments",
                        to="events.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_assignments",
                        to="people.person",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="seating.table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RelationshipEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive (should sit together)"),
                            ("negative", "Conflict (must not sit together)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_hard_constraint", models.BooleanField(default=False)),
                (
                    "person_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_edges_as_a",
                        to="people.person",
                    ),
                ),
                (
                    "person_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_edges_as_b",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person_a", "person_b"), name="unique_relationship_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("person_a", models.F("person_b")), _negated=True
                        ),
                        name="relationship_not_self",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_table_name_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="seatpin",
            constraint=models.UniqueConstraint(
                fields=("event", "person"), name="one_pin_per_person_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="tableassignment",
            constraint=models.UniqueConstraint(
                fields=("event", "person"), name="one_assignment_per_person_per_event"
            ),
        ),
    ]
