# Generated by Django 5.2.15 on 2026-07-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seatingweights",
            options={"verbose_name_plural": "Seating weights"},
        ),
    ]
